# 10-create-ca.yaml - create our own CA
# yamllint disable rule:line-length
# Based on: https://docs.ansible.com/ansible/latest/collections/community/crypto/docsite/guide_ownca.html
---
- name: Run local script
  hosts: localhost
  connection: local
  gather_facts: true
  tasks:
    - name: Load PKI dir and CA key password
      ansible.builtin.include_vars:
        file: /etc/opt/ansible-vars.yaml
        name: lvars
    - name: Debug CA key path
      ansible.builtin.debug:
        msg: "CA key path='{{ lvars.own_ca.ca_key_path }}'"
    # now tough stuff - generating our own key (secret is in /etc/opt/ansible-vars.yaml)
    # from: https://docs.ansible.com/ansible/latest/collections/community/crypto/docsite/guide_ownca.html#how-to-create-a-small-ca
    - name: Create private key with password protection
      community.crypto.openssl_privatekey:
        path: "{{ lvars.own_ca.ca_key_path }}"
        cipher: auto
        passphrase: "{{ lvars.own_ca.secret_ca_passphrase }}"
    - name: Create certificate signing request (CSR) for CA certificate
      community.crypto.openssl_csr_pipe:
        privatekey_path: "{{ lvars.own_ca.ca_key_path }}"
        privatekey_passphrase: "{{ lvars.own_ca.secret_ca_passphrase }}"
        common_name: Ansible CA
        use_common_name_for_san: false  # since we do not specify SANs, don't use CN as a SAN
        basic_constraints:
          - 'CA:TRUE'
        basic_constraints_critical: true
        key_usage:
          - keyCertSign
        key_usage_critical: true
      register: ca_csr
    - name: Create self-signed CA certificate from CSR
      community.crypto.x509_certificate:
        path: "{{ lvars.own_ca.ca_cert_path }}"
        csr_content: "{{ ca_csr.csr }}"
        privatekey_path: "{{ lvars.own_ca.ca_key_path }}"
        privatekey_passphrase: "{{ lvars.own_ca.secret_ca_passphrase }}"
        provider: selfsigned
    - name: Print CA cert pathname
      ansible.builtin.debug:
        msg: "CA cert generated to='{{ lvars.own_ca.ca_cert_path }}'"
